FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /app

COPY ["WorkList.Api.csproj", "./"]
RUN dotnet restore

COPY . .

EXPOSE 8080

ENTRYPOINT ["dotnet", "watch", "run", "--no-launch-profile", "--urls", "http://0.0.0.0:8080"]